### ISSUE TITLE
从上个版本更新后无法正常使用

### ISSUE THREAD

**Issue by deluo** [guangzan/tinytab#1]
我是从上个版本自动更新后无法正常打开
edge浏览器，JSON.parse(localStorage.theme)这段代码报错了，应该是最新的版本改了localStorage中theme的存储格式吧

**Comment by guangzan** [comment]
重新安装试试

**Comment by guangzan** [comment]
我无法复现这个问题，我想你可以通过重装解决它，感谢反馈。
